apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
 name: cts-app
 namespace: app
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: cts-app
 minReplicas: 3
 metrics:
    - resource:
        name: cpu
        target:
          averageUtilization: 85
          type: Utilization
      type: Resource
 maxReplicas: 6